// This file is auto-generated by @hey-api/openapi-ts

export const AllocazionePublicSchema = {
    properties: {
        liquidita_cents: {
            type: 'integer',
            title: 'Liquidita Cents'
        },
        liquidita_allocata_cents: {
            type: 'integer',
            title: 'Liquidita Allocata Cents'
        },
        risparmio_libero_cents: {
            type: 'integer',
            title: 'Risparmio Libero Cents'
        },
        spesa_media_mensile_cents: {
            type: 'integer',
            title: 'Spesa Media Mensile Cents'
        },
        mesi_cuscinetto: {
            type: 'integer',
            title: 'Mesi Cuscinetto'
        },
        cuscinetto_cents: {
            type: 'integer',
            title: 'Cuscinetto Cents'
        },
        sotto_cuscinetto: {
            type: 'boolean',
            title: 'Sotto Cuscinetto'
        }
    },
    type: 'object',
    required: ['liquidita_cents', 'liquidita_allocata_cents', 'risparmio_libero_cents', 'spesa_media_mensile_cents', 'mesi_cuscinetto', 'cuscinetto_cents', 'sotto_cuscinetto'],
    title: 'AllocazionePublic'
} as const;

export const BeneImmobileCreateSchema = {
    properties: {
        nome: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Nome'
        },
        prezzo_cents: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Prezzo Cents'
        }
    },
    type: 'object',
    required: ['nome', 'prezzo_cents'],
    title: 'BeneImmobileCreate'
} as const;

export const BeneImmobilePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        },
        prezzo_cents: {
            type: 'integer',
            title: 'Prezzo Cents'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'nome', 'prezzo_cents'],
    title: 'BeneImmobilePublic'
} as const;

export const BeneImmobileUpdateSchema = {
    properties: {
        nome: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome'
        },
        prezzo_cents: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prezzo Cents'
        }
    },
    type: 'object',
    title: 'BeneImmobileUpdate'
} as const;

export const BeneMobileCreateSchema = {
    properties: {
        nome: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Nome'
        },
        prezzo_cents: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Prezzo Cents'
        },
        data_acquisto: {
            type: 'string',
            format: 'date',
            title: 'Data Acquisto'
        },
        svalutazione_percentuale: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Svalutazione Percentuale'
        }
    },
    type: 'object',
    required: ['nome', 'prezzo_cents', 'data_acquisto', 'svalutazione_percentuale'],
    title: 'BeneMobileCreate'
} as const;

export const BeneMobilePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        },
        prezzo_cents: {
            type: 'integer',
            title: 'Prezzo Cents'
        },
        data_acquisto: {
            type: 'string',
            format: 'date',
            title: 'Data Acquisto'
        },
        svalutazione_percentuale: {
            type: 'number',
            title: 'Svalutazione Percentuale'
        },
        valore_cents: {
            type: 'integer',
            title: 'Valore Cents'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'nome', 'prezzo_cents', 'data_acquisto', 'svalutazione_percentuale', 'valore_cents'],
    title: 'BeneMobilePublic'
} as const;

export const BeneMobileUpdateSchema = {
    properties: {
        nome: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome'
        },
        prezzo_cents: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prezzo Cents'
        },
        data_acquisto: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Acquisto'
        },
        svalutazione_percentuale: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Svalutazione Percentuale'
        }
    },
    type: 'object',
    title: 'BeneMobileUpdate'
} as const;

export const BilancioPeriodoSchema = {
    properties: {
        period: {
            type: 'string',
            title: 'Period'
        },
        start: {
            type: 'string',
            format: 'date',
            title: 'Start'
        },
        end: {
            type: 'string',
            format: 'date',
            title: 'End'
        },
        netto_cents: {
            type: 'integer',
            title: 'Netto Cents'
        },
        entrate_cents: {
            type: 'integer',
            title: 'Entrate Cents'
        },
        spese_cents: {
            type: 'integer',
            title: 'Spese Cents'
        },
        spese_per_categoria: {
            items: {
                '$ref': '#/components/schemas/CategoriaSpesa'
            },
            type: 'array',
            title: 'Spese Per Categoria'
        }
    },
    type: 'object',
    required: ['period', 'start', 'end', 'netto_cents', 'entrate_cents', 'spese_cents', 'spese_per_categoria'],
    title: 'BilancioPeriodo'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CategoriaCreateSchema = {
    properties: {
        nome: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Nome'
        },
        tipo: {
            '$ref': '#/components/schemas/CategoriaTipo'
        }
    },
    type: 'object',
    required: ['nome', 'tipo'],
    title: 'CategoriaCreate'
} as const;

export const CategoriaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        },
        tipo: {
            type: 'string',
            title: 'Tipo'
        },
        secchiello_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secchiello Id'
        },
        is_system: {
            type: 'boolean',
            title: 'Is System',
            default: false
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'nome', 'tipo'],
    title: 'CategoriaPublic'
} as const;

export const CategoriaSpesaSchema = {
    properties: {
        categoria_id: {
            type: 'string',
            format: 'uuid',
            title: 'Categoria Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        },
        total_cents: {
            type: 'integer',
            title: 'Total Cents'
        }
    },
    type: 'object',
    required: ['categoria_id', 'nome', 'total_cents'],
    title: 'CategoriaSpesa'
} as const;

export const CategoriaTipoSchema = {
    type: 'string',
    enum: ['spesa', 'entrata'],
    title: 'CategoriaTipo'
} as const;

export const CategoriaUpdateSchema = {
    properties: {
        nome: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome'
        },
        secchiello_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secchiello Id'
        }
    },
    type: 'object',
    title: 'CategoriaUpdate'
} as const;

export const CategorieListSchema = {
    properties: {
        spesa: {
            items: {
                '$ref': '#/components/schemas/CategoriaPublic'
            },
            type: 'array',
            title: 'Spesa'
        },
        entrata: {
            items: {
                '$ref': '#/components/schemas/CategoriaPublic'
            },
            type: 'array',
            title: 'Entrata'
        }
    },
    type: 'object',
    required: ['spesa', 'entrata'],
    title: 'CategorieList'
} as const;

export const DriftPreviewSchema = {
    properties: {
        liquidita_calcolata_cents: {
            type: 'integer',
            title: 'Liquidita Calcolata Cents'
        },
        drift_cents: {
            type: 'integer',
            title: 'Drift Cents'
        },
        drift_percent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Drift Percent'
        }
    },
    type: 'object',
    required: ['liquidita_calcolata_cents', 'drift_cents', 'drift_percent'],
    title: 'DriftPreview'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IntervalloUpdateSchema = {
    properties: {
        intervallo_riconciliazione_giorni: {
            type: 'integer',
            minimum: 1,
            title: 'Intervallo Riconciliazione Giorni'
        }
    },
    type: 'object',
    required: ['intervallo_riconciliazione_giorni'],
    title: 'IntervalloUpdate'
} as const;

export const InvestimentoCreateSchema = {
    properties: {
        nome: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Nome'
        }
    },
    type: 'object',
    required: ['nome'],
    title: 'InvestimentoCreate'
} as const;

export const InvestimentoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        },
        capitale_versato_cents: {
            type: 'integer',
            title: 'Capitale Versato Cents'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'nome', 'capitale_versato_cents'],
    title: 'InvestimentoPublic'
} as const;

export const InvestimentoUpdateSchema = {
    properties: {
        nome: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome'
        }
    },
    type: 'object',
    title: 'InvestimentoUpdate'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LiquiditaInizialePublicSchema = {
    properties: {
        value_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value Cents'
        },
        is_set: {
            type: 'boolean',
            title: 'Is Set'
        }
    },
    type: 'object',
    required: ['is_set'],
    title: 'LiquiditaInizialePublic'
} as const;

export const LiquiditaInizialeSetSchema = {
    properties: {
        value_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Value Cents'
        }
    },
    type: 'object',
    required: ['value_cents'],
    title: 'LiquiditaInizialeSet'
} as const;

export const LiquiditaInizialeSetResponseSchema = {
    properties: {
        value_cents: {
            type: 'integer',
            title: 'Value Cents'
        },
        is_set: {
            type: 'boolean',
            title: 'Is Set',
            default: true
        },
        rebaselined: {
            type: 'boolean',
            title: 'Rebaselined'
        }
    },
    type: 'object',
    required: ['value_cents', 'rebaselined'],
    title: 'LiquiditaInizialeSetResponse'
} as const;

export const LiquiditaPublicSchema = {
    properties: {
        value_cents: {
            type: 'integer',
            title: 'Value Cents'
        },
        iniziale_is_set: {
            type: 'boolean',
            title: 'Iniziale Is Set'
        }
    },
    type: 'object',
    required: ['value_cents', 'iniziale_is_set'],
    title: 'LiquiditaPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MovimentoCreateSchema = {
    properties: {
        tipo: {
            '$ref': '#/components/schemas/CategoriaTipo'
        },
        amount_cents: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Amount Cents'
        },
        data: {
            type: 'string',
            format: 'date',
            title: 'Data'
        },
        categoria_id: {
            type: 'string',
            format: 'uuid',
            title: 'Categoria Id'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        secchiello_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secchiello Id'
        }
    },
    type: 'object',
    required: ['tipo', 'amount_cents', 'data', 'categoria_id'],
    title: 'MovimentoCreate'
} as const;

export const MovimentoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tipo: {
            type: 'string',
            title: 'Tipo'
        },
        amount_cents: {
            type: 'integer',
            title: 'Amount Cents'
        },
        data: {
            type: 'string',
            format: 'date',
            title: 'Data'
        },
        categoria_id: {
            type: 'string',
            format: 'uuid',
            title: 'Categoria Id'
        },
        secchiello_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secchiello Id'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'tipo', 'amount_cents', 'data', 'categoria_id'],
    title: 'MovimentoPublic'
} as const;

export const MovimentoUpdateSchema = {
    properties: {
        amount_cents: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount Cents'
        },
        data: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        },
        categoria_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Categoria Id'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        secchiello_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secchiello Id'
        }
    },
    type: 'object',
    title: 'MovimentoUpdate'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PatrimonioComponenteSchema = {
    properties: {
        chiave: {
            type: 'string',
            title: 'Chiave'
        },
        valore_cents: {
            type: 'integer',
            title: 'Valore Cents'
        }
    },
    type: 'object',
    required: ['chiave', 'valore_cents'],
    title: 'PatrimonioComponente'
} as const;

export const PatrimonioPublicSchema = {
    properties: {
        totale_cents: {
            type: 'integer',
            title: 'Totale Cents'
        },
        liquidita_cents: {
            type: 'integer',
            title: 'Liquidita Cents'
        },
        capitale_versato_cents: {
            type: 'integer',
            title: 'Capitale Versato Cents'
        },
        beni_immobili_cents: {
            type: 'integer',
            title: 'Beni Immobili Cents'
        },
        beni_mobili_cents: {
            type: 'integer',
            title: 'Beni Mobili Cents'
        },
        componenti: {
            items: {
                '$ref': '#/components/schemas/PatrimonioComponente'
            },
            type: 'array',
            title: 'Componenti'
        }
    },
    type: 'object',
    required: ['totale_cents', 'liquidita_cents', 'capitale_versato_cents', 'beni_immobili_cents', 'beni_mobili_cents', 'componenti'],
    title: 'PatrimonioPublic'
} as const;

export const PeriodicitaSchema = {
    type: 'string',
    enum: ['monthly', 'quarterly', 'semiannual', 'annual', 'custom'],
    title: 'Periodicita'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PromemoriaPublicSchema = {
    properties: {
        due: {
            type: 'boolean',
            title: 'Due'
        },
        giorni_dall_ultima: {
            type: 'integer',
            title: 'Giorni Dall Ultima'
        },
        data_ultima_riconciliazione: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Ultima Riconciliazione'
        },
        intervallo_giorni: {
            type: 'integer',
            title: 'Intervallo Giorni'
        },
        drift_aperto_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Drift Aperto Cents'
        }
    },
    type: 'object',
    required: ['due', 'giorni_dall_ultima', 'data_ultima_riconciliazione', 'intervallo_giorni'],
    title: 'PromemoriaPublic'
} as const;

export const RiconciliazioneCreateSchema = {
    properties: {
        liquidita_reale_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Liquidita Reale Cents'
        },
        esito: {
            '$ref': '#/components/schemas/RiconciliazioneEsito'
        }
    },
    type: 'object',
    required: ['liquidita_reale_cents', 'esito'],
    title: 'RiconciliazioneCreate'
} as const;

export const RiconciliazioneEsitoSchema = {
    type: 'string',
    enum: ['chiusa', 'acknowledged_open'],
    title: 'RiconciliazioneEsito'
} as const;

export const RiconciliazionePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        liquidita_reale_cents: {
            type: 'integer',
            title: 'Liquidita Reale Cents'
        },
        liquidita_calcolata_cents: {
            type: 'integer',
            title: 'Liquidita Calcolata Cents'
        },
        drift_cents: {
            type: 'integer',
            title: 'Drift Cents'
        },
        drift_percent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Drift Percent'
        },
        data_riconciliazione: {
            type: 'string',
            format: 'date',
            title: 'Data Riconciliazione'
        },
        esito: {
            type: 'string',
            title: 'Esito'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'liquidita_reale_cents', 'liquidita_calcolata_cents', 'drift_cents', 'drift_percent', 'data_riconciliazione', 'esito'],
    title: 'RiconciliazionePublic'
} as const;

export const RiconciliazioneRealeInputSchema = {
    properties: {
        liquidita_reale_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Liquidita Reale Cents'
        }
    },
    type: 'object',
    required: ['liquidita_reale_cents'],
    title: 'RiconciliazioneRealeInput'
} as const;

export const SecchielloCreateSchema = {
    properties: {
        nome: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Nome'
        },
        importo_previsto_cents: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Importo Previsto Cents'
        },
        periodicita: {
            '$ref': '#/components/schemas/Periodicita'
        },
        intervallo_mesi: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intervallo Mesi'
        },
        prossima_scadenza: {
            type: 'string',
            format: 'date',
            title: 'Prossima Scadenza'
        }
    },
    type: 'object',
    required: ['nome', 'importo_previsto_cents', 'periodicita', 'prossima_scadenza'],
    title: 'SecchielloCreate'
} as const;

export const SecchielloPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        },
        importo_previsto_cents: {
            type: 'integer',
            title: 'Importo Previsto Cents'
        },
        periodicita: {
            type: 'string',
            title: 'Periodicita'
        },
        intervallo_mesi: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intervallo Mesi'
        },
        prossima_scadenza: {
            type: 'string',
            format: 'date',
            title: 'Prossima Scadenza'
        },
        data_inizio: {
            type: 'string',
            format: 'date',
            title: 'Data Inizio'
        },
        saldo_cents: {
            type: 'integer',
            title: 'Saldo Cents'
        },
        quota_cents: {
            type: 'integer',
            title: 'Quota Cents'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'nome', 'importo_previsto_cents', 'periodicita', 'intervallo_mesi', 'prossima_scadenza', 'data_inizio', 'saldo_cents', 'quota_cents'],
    title: 'SecchielloPublic'
} as const;

export const SecchielloUpdateSchema = {
    properties: {
        nome: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome'
        },
        importo_previsto_cents: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Importo Previsto Cents'
        },
        periodicita: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Periodicita'
                },
                {
                    type: 'null'
                }
            ]
        },
        intervallo_mesi: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intervallo Mesi'
        },
        prossima_scadenza: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prossima Scadenza'
        }
    },
    type: 'object',
    title: 'SecchielloUpdate'
} as const;

export const StatisticheSchema = {
    properties: {
        period: {
            type: 'string',
            title: 'Period'
        },
        start: {
            type: 'string',
            format: 'date',
            title: 'Start'
        },
        end: {
            type: 'string',
            format: 'date',
            title: 'End'
        },
        trend: {
            items: {
                '$ref': '#/components/schemas/TrendPunto'
            },
            type: 'array',
            title: 'Trend'
        },
        pie: {
            items: {
                '$ref': '#/components/schemas/CategoriaSpesa'
            },
            type: 'array',
            title: 'Pie'
        },
        has_trend: {
            type: 'boolean',
            title: 'Has Trend'
        },
        has_pie: {
            type: 'boolean',
            title: 'Has Pie'
        }
    },
    type: 'object',
    required: ['period', 'start', 'end', 'trend', 'pie', 'has_trend', 'has_pie'],
    title: 'Statistiche'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TrendPuntoSchema = {
    properties: {
        mese: {
            type: 'string',
            title: 'Mese'
        },
        entrate_cents: {
            type: 'integer',
            title: 'Entrate Cents'
        },
        spese_cents: {
            type: 'integer',
            title: 'Spese Cents'
        },
        netto_cents: {
            type: 'integer',
            title: 'Netto Cents'
        }
    },
    type: 'object',
    required: ['mese', 'entrate_cents', 'spese_cents', 'netto_cents'],
    title: 'TrendPunto'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const UtenteLoginSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            minLength: 3,
            title: 'Username'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UtenteLogin'
} as const;

export const UtentePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        session_timeout_days: {
            type: 'integer',
            title: 'Session Timeout Days'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'username', 'session_timeout_days'],
    title: 'UtentePublic'
} as const;

export const UtenteRecoverSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            minLength: 3,
            title: 'Username'
        },
        recovery_code: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Recovery Code'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['username', 'recovery_code', 'new_password'],
    title: 'UtenteRecover'
} as const;

export const UtenteRegisterSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            minLength: 3,
            title: 'Username'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UtenteRegister'
} as const;

export const UtenteRegisterResponseSchema = {
    properties: {
        utente: {
            '$ref': '#/components/schemas/UtentePublic'
        },
        recovery_code: {
            type: 'string',
            title: 'Recovery Code'
        }
    },
    type: 'object',
    required: ['utente', 'recovery_code'],
    title: 'UtenteRegisterResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VersamentoPacCreateSchema = {
    properties: {
        importo_cents: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Importo Cents'
        },
        data: {
            type: 'string',
            format: 'date',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['importo_cents', 'data'],
    title: 'VersamentoPacCreate'
} as const;

export const VersamentoPacPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        investimento_id: {
            type: 'string',
            format: 'uuid',
            title: 'Investimento Id'
        },
        importo_cents: {
            type: 'integer',
            title: 'Importo Cents'
        },
        data: {
            type: 'string',
            format: 'date',
            title: 'Data'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'investimento_id', 'importo_cents', 'data'],
    title: 'VersamentoPacPublic'
} as const;

export const VersamentoPacUpdateSchema = {
    properties: {
        importo_cents: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Importo Cents'
        },
        data: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    title: 'VersamentoPacUpdate'
} as const;