// This file is auto-generated by @hey-api/openapi-ts

export type AllocazionePublic = {
    liquidita_cents: number;
    liquidita_allocata_cents: number;
    risparmio_libero_cents: number;
    spesa_media_mensile_cents: number;
    mesi_cuscinetto: number;
    cuscinetto_cents: number;
    sotto_cuscinetto: boolean;
};

export type BilancioPeriodo = {
    period: string;
    start: string;
    end: string;
    netto_cents: number;
    entrate_cents: number;
    spese_cents: number;
    spese_per_categoria: Array<CategoriaSpesa>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoriaCreate = {
    nome: string;
    tipo: CategoriaTipo;
};

export type CategoriaPublic = {
    id: string;
    nome: string;
    tipo: string;
    secchiello_id?: (string | null);
    created_at?: (string | null);
};

export type CategoriaSpesa = {
    categoria_id: string;
    nome: string;
    total_cents: number;
};

export type CategoriaTipo = 'spesa' | 'entrata';

export type CategoriaUpdate = {
    nome?: (string | null);
    secchiello_id?: (string | null);
};

export type CategorieList = {
    spesa: Array<CategoriaPublic>;
    entrata: Array<CategoriaPublic>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LiquiditaInizialePublic = {
    value_cents?: (number | null);
    is_set: boolean;
};

export type LiquiditaInizialeSet = {
    value_cents: number;
};

export type LiquiditaInizialeSetResponse = {
    value_cents: number;
    is_set?: boolean;
    rebaselined: boolean;
};

export type LiquiditaPublic = {
    value_cents: number;
    iniziale_is_set: boolean;
};

export type Message = {
    message: string;
};

export type MovimentoCreate = {
    tipo: CategoriaTipo;
    amount_cents: number;
    data: string;
    categoria_id: string;
    note?: (string | null);
    secchiello_id?: (string | null);
};

export type MovimentoPublic = {
    id: string;
    tipo: string;
    amount_cents: number;
    data: string;
    categoria_id: string;
    secchiello_id?: (string | null);
    note?: (string | null);
    created_at?: (string | null);
};

export type MovimentoUpdate = {
    amount_cents?: (number | null);
    data?: (string | null);
    categoria_id?: (string | null);
    note?: (string | null);
    secchiello_id?: (string | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Periodicita = 'monthly' | 'quarterly' | 'semiannual' | 'annual' | 'custom';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SecchielloCreate = {
    nome: string;
    importo_previsto_cents: number;
    periodicita: Periodicita;
    intervallo_mesi?: (number | null);
    prossima_scadenza: string;
};

export type SecchielloPublic = {
    id: string;
    nome: string;
    importo_previsto_cents: number;
    periodicita: string;
    intervallo_mesi: (number | null);
    prossima_scadenza: string;
    data_inizio: string;
    saldo_cents: number;
    quota_cents: number;
    created_at?: (string | null);
};

export type SecchielloUpdate = {
    nome?: (string | null);
    importo_previsto_cents?: (number | null);
    periodicita?: (Periodicita | null);
    intervallo_mesi?: (number | null);
    prossima_scadenza?: (string | null);
};

export type Statistiche = {
    period: string;
    start: string;
    end: string;
    trend: Array<TrendPunto>;
    pie: Array<CategoriaSpesa>;
    has_trend: boolean;
    has_pie: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TrendPunto = {
    mese: string;
    entrate_cents: number;
    spese_cents: number;
    netto_cents: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type UtenteLogin = {
    username: string;
    password: string;
};

export type UtentePublic = {
    id: string;
    username: string;
    session_timeout_days: number;
    created_at?: (string | null);
};

export type UtenteRecover = {
    username: string;
    recovery_code: string;
    new_password: string;
};

export type UtenteRegister = {
    username: string;
    password: string;
};

export type UtenteRegisterResponse = {
    utente: UtentePublic;
    recovery_code: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthRegisterData = {
    requestBody: UtenteRegister;
};

export type AuthRegisterResponse = (UtenteRegisterResponse);

export type AuthLoginData = {
    requestBody: UtenteLogin;
};

export type AuthLoginResponse = (Token);

export type AuthReadMeResponse = (UtentePublic);

export type AuthLogoutResponse = (Message);

export type AuthRecoverData = {
    requestBody: UtenteRecover;
};

export type AuthRecoverResponse = (Message);

export type CategorieListCategorieResponse = (CategorieList);

export type CategorieCreateCategoriaData = {
    requestBody: CategoriaCreate;
};

export type CategorieCreateCategoriaResponse = (CategoriaPublic);

export type CategorieUpdateCategoriaData = {
    categoriaId: string;
    requestBody: CategoriaUpdate;
};

export type CategorieUpdateCategoriaResponse = (CategoriaPublic);

export type CategorieDeleteCategoriaData = {
    categoriaId: string;
};

export type CategorieDeleteCategoriaResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LiquiditaReadLiquiditaResponse = (LiquiditaPublic);

export type LiquiditaReadLiquiditaInizialeResponse = (LiquiditaInizialePublic);

export type LiquiditaSetLiquiditaInizialeData = {
    requestBody: LiquiditaInizialeSet;
};

export type LiquiditaSetLiquiditaInizialeResponse = (LiquiditaInizialeSetResponse);

export type LiquiditaAllocazioneData = {
    mesi?: number;
};

export type LiquiditaAllocazioneResponse = (AllocazionePublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MovimentiCreateMovimentoData = {
    requestBody: MovimentoCreate;
};

export type MovimentiCreateMovimentoResponse = (MovimentoPublic);

export type MovimentiListMovimentiData = {
    categoriaId?: (string | null);
    end?: (string | null);
    start?: (string | null);
};

export type MovimentiListMovimentiResponse = (Array<MovimentoPublic>);

export type MovimentiUpdateMovimentoData = {
    movimentoId: string;
    requestBody: MovimentoUpdate;
};

export type MovimentiUpdateMovimentoResponse = (MovimentoPublic);

export type MovimentiDeleteMovimentoData = {
    movimentoId: string;
};

export type MovimentiDeleteMovimentoResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RiepilogoBilancioData = {
    anchor: string;
    period?: string;
};

export type RiepilogoBilancioResponse = (BilancioPeriodo);

export type RiepilogoStatisticheData = {
    anchor: string;
    period?: string;
};

export type RiepilogoStatisticheResponse = (Statistiche);

export type SecchielliListSecchielliResponse = (Array<SecchielloPublic>);

export type SecchielliCreateSecchielloData = {
    requestBody: SecchielloCreate;
};

export type SecchielliCreateSecchielloResponse = (SecchielloPublic);

export type SecchielliGetSecchielloData = {
    secchielloId: string;
};

export type SecchielliGetSecchielloResponse = (SecchielloPublic);

export type SecchielliUpdateSecchielloData = {
    requestBody: SecchielloUpdate;
    secchielloId: string;
};

export type SecchielliUpdateSecchielloResponse = (SecchielloPublic);

export type SecchielliDeleteSecchielloData = {
    secchielloId: string;
};

export type SecchielliDeleteSecchielloResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);