/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutStatisticheRouteImport } from './routes/_layout/statistiche'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRiconciliazioneRouteImport } from './routes/_layout/riconciliazione'
import { Route as LayoutPatrimonioRouteImport } from './routes/_layout/patrimonio'
import { Route as LayoutLiquiditaRouteImport } from './routes/_layout/liquidita'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutCategorieRouteImport } from './routes/_layout/categorie'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStatisticheRoute = LayoutStatisticheRouteImport.update({
  id: '/statistiche',
  path: '/statistiche',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRiconciliazioneRoute = LayoutRiconciliazioneRouteImport.update({
  id: '/riconciliazione',
  path: '/riconciliazione',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatrimonioRoute = LayoutPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLiquiditaRoute = LayoutLiquiditaRouteImport.update({
  id: '/liquidita',
  path: '/liquidita',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategorieRoute = LayoutCategorieRouteImport.update({
  id: '/categorie',
  path: '/categorie',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categorie': typeof LayoutCategorieRoute
  '/items': typeof LayoutItemsRoute
  '/liquidita': typeof LayoutLiquiditaRoute
  '/patrimonio': typeof LayoutPatrimonioRoute
  '/riconciliazione': typeof LayoutRiconciliazioneRoute
  '/settings': typeof LayoutSettingsRoute
  '/statistiche': typeof LayoutStatisticheRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categorie': typeof LayoutCategorieRoute
  '/items': typeof LayoutItemsRoute
  '/liquidita': typeof LayoutLiquiditaRoute
  '/patrimonio': typeof LayoutPatrimonioRoute
  '/riconciliazione': typeof LayoutRiconciliazioneRoute
  '/settings': typeof LayoutSettingsRoute
  '/statistiche': typeof LayoutStatisticheRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/categorie': typeof LayoutCategorieRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/liquidita': typeof LayoutLiquiditaRoute
  '/_layout/patrimonio': typeof LayoutPatrimonioRoute
  '/_layout/riconciliazione': typeof LayoutRiconciliazioneRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/statistiche': typeof LayoutStatisticheRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/categorie'
    | '/items'
    | '/liquidita'
    | '/patrimonio'
    | '/riconciliazione'
    | '/settings'
    | '/statistiche'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/categorie'
    | '/items'
    | '/liquidita'
    | '/patrimonio'
    | '/riconciliazione'
    | '/settings'
    | '/statistiche'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/categorie'
    | '/_layout/items'
    | '/_layout/liquidita'
    | '/_layout/patrimonio'
    | '/_layout/riconciliazione'
    | '/_layout/settings'
    | '/_layout/statistiche'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/statistiche': {
      id: '/_layout/statistiche'
      path: '/statistiche'
      fullPath: '/statistiche'
      preLoaderRoute: typeof LayoutStatisticheRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/riconciliazione': {
      id: '/_layout/riconciliazione'
      path: '/riconciliazione'
      fullPath: '/riconciliazione'
      preLoaderRoute: typeof LayoutRiconciliazioneRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patrimonio': {
      id: '/_layout/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof LayoutPatrimonioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/liquidita': {
      id: '/_layout/liquidita'
      path: '/liquidita'
      fullPath: '/liquidita'
      preLoaderRoute: typeof LayoutLiquiditaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categorie': {
      id: '/_layout/categorie'
      path: '/categorie'
      fullPath: '/categorie'
      preLoaderRoute: typeof LayoutCategorieRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCategorieRoute: typeof LayoutCategorieRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutLiquiditaRoute: typeof LayoutLiquiditaRoute
  LayoutPatrimonioRoute: typeof LayoutPatrimonioRoute
  LayoutRiconciliazioneRoute: typeof LayoutRiconciliazioneRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStatisticheRoute: typeof LayoutStatisticheRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCategorieRoute: LayoutCategorieRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutLiquiditaRoute: LayoutLiquiditaRoute,
  LayoutPatrimonioRoute: LayoutPatrimonioRoute,
  LayoutRiconciliazioneRoute: LayoutRiconciliazioneRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStatisticheRoute: LayoutStatisticheRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
